"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _admin_brand_management from './admin-brand-management.bones.json'
import _brand_creators_browser from './brand-creators-browser.bones.json'

configureBoneyard({"color":"#ece7dd","darkColor":"#26221c","animate":"shimmer","shimmerColor":"#f6f1e8","darkShimmerColor":"#312b24","speed":"2s","shimmerAngle":110})

registerBones({
  "admin-brand-management": _admin_brand_management,
  "brand-creators-browser": _brand_creators_browser,
})
