import type { Creator, CreatorProfile } from "./types";

export const MOCK_CREATORS: Creator[] = [
  {
    id: "1",
    name: "Riya Sharma",
    location: "Delhi",
    rating: 4.8,
    reviewCount: 120,
    startingPrice: 2000,
    ordersCompleted: 95,
    thumbnail: "/globe.svg",
    tags: ["Fashion", "Hindi", "Store Visit"],
    available: true,
    storeVisit: true,
    travelAvailable: true,
    gender: "female",
    category: "Fashion",
  },
  {
    id: "2",
    name: "Arjun Mehta",
    location: "Mumbai",
    rating: 4.9,
    reviewCount: 200,
    startingPrice: 3500,
    ordersCompleted: 180,
    thumbnail: "/globe.svg",
    tags: ["Tech", "English", "Unboxing"],
    available: true,
    storeVisit: false,
    travelAvailable: true,
    gender: "male",
    category: "Tech",
  },
  {
    id: "3",
    name: "Priya Patel",
    location: "Bangalore",
    rating: 4.7,
    reviewCount: 85,
    startingPrice: 1500,
    ordersCompleted: 62,
    thumbnail: "/globe.svg",
    tags: ["Beauty", "Hindi", "Reels"],
    available: true,
    storeVisit: true,
    travelAvailable: false,
    gender: "female",
    category: "Beauty",
  },
  {
    id: "4",
    name: "Karan Singh",
    location: "Jaipur",
    rating: 4.6,
    reviewCount: 54,
    startingPrice: 1800,
    ordersCompleted: 40,
    thumbnail: "/globe.svg",
    tags: ["Food", "Hindi", "Store Visit"],
    available: true,
    storeVisit: true,
    travelAvailable: true,
    gender: "male",
    category: "Food",
  },
  {
    id: "5",
    name: "Ananya Iyer",
    location: "Chennai",
    rating: 4.9,
    reviewCount: 150,
    startingPrice: 4000,
    ordersCompleted: 130,
    thumbnail: "/globe.svg",
    tags: ["Lifestyle", "English", "Tamil"],
    available: true,
    storeVisit: false,
    travelAvailable: true,
    gender: "female",
    category: "Lifestyle",
  },
  {
    id: "6",
    name: "Vikram Joshi",
    location: "Pune",
    rating: 4.5,
    reviewCount: 70,
    startingPrice: 2500,
    ordersCompleted: 55,
    thumbnail: "/globe.svg",
    tags: ["Fitness", "English", "Hindi"],
    available: true,
    storeVisit: false,
    travelAvailable: false,
    gender: "male",
    category: "Fitness",
  },
  {
    id: "7",
    name: "Sneha Reddy",
    location: "Hyderabad",
    rating: 4.8,
    reviewCount: 110,
    startingPrice: 3000,
    ordersCompleted: 88,
    thumbnail: "/globe.svg",
    tags: ["Fashion", "Telugu", "Store Visit"],
    available: true,
    storeVisit: true,
    travelAvailable: true,
    gender: "female",
    category: "Fashion",
  },
  {
    id: "8",
    name: "Rohan Kapoor",
    location: "Delhi",
    rating: 4.4,
    reviewCount: 45,
    startingPrice: 2200,
    ordersCompleted: 32,
    thumbnail: "/globe.svg",
    tags: ["Tech", "Hindi", "Unboxing"],
    available: true,
    storeVisit: false,
    travelAvailable: true,
    gender: "male",
    category: "Tech",
  },
];

export function getCreatorProfile(id: string): CreatorProfile | undefined {
  const creator = MOCK_CREATORS.find((c) => c.id === id);
  if (!creator) return undefined;

  return {
    ...creator,
    bio: "Passionate content creator specializing in authentic, scroll-stopping UGC. I bring brands to life through storytelling that resonates with real audiences.",
    languages: ["Hindi", "English"],
    acceptsLingerie: false,
    responseTime: "Under 2 hours",
    joinedDate: "2024",
    portfolio: [
      { id: "p1", title: "Product Unboxing", thumbnail: "/globe.svg", views: 12400, category: "Unboxing" },
      { id: "p2", title: "Day in My Life", thumbnail: "/globe.svg", views: 8700, category: "Lifestyle" },
      { id: "p3", title: "Brand Review", thumbnail: "/globe.svg", views: 15200, category: "Review" },
      { id: "p4", title: "Get Ready With Me", thumbnail: "/globe.svg", views: 9300, category: "Beauty" },
      { id: "p5", title: "Try-On Haul", thumbnail: "/globe.svg", views: 21000, category: "Fashion" },
      { id: "p6", title: "Skincare Routine", thumbnail: "/globe.svg", views: 6800, category: "Beauty" },
    ],
    packages: [
      {
        id: "pkg-basic",
        tier: "basic",
        label: "Basic",
        price: creator.startingPrice,
        deliveryDays: 3,
        revisions: 1,
        features: ["1 UGC Video (30–60s)", "Basic editing", "Vertical format (9:16)", "Usage rights included"],
      },
      {
        id: "pkg-standard",
        tier: "standard",
        label: "Standard",
        price: Math.round(creator.startingPrice * 1.8),
        deliveryDays: 5,
        revisions: 2,
        features: ["2 UGC Videos (30–60s)", "Professional editing", "Vertical + Square formats", "Usage rights included", "1 concept variation"],
      },
      {
        id: "pkg-premium",
        tier: "premium",
        label: "Premium",
        price: Math.round(creator.startingPrice * 3),
        deliveryDays: 7,
        revisions: 3,
        features: ["3 UGC Videos (30–90s)", "Premium editing + motion graphics", "All formats", "Full usage rights", "2 concept variations", "Raw footage included"],
      },
    ],
    addOns: [
      { id: "addon-travel", label: "Travel fee", price: 1000 },
      { id: "addon-editing", label: "Advanced editing", price: 800 },
      { id: "addon-script", label: "Script writing", price: 500 },
      { id: "addon-express", label: "Express delivery (24h)", price: 700 },
    ],
    reviews: [
      { id: "r1", author: "Meera K.", rating: 5, date: "2 weeks ago", comment: "Amazing work! The video exceeded our expectations. Great communication throughout the project.", brand: "GlowSkin" },
      { id: "r2", author: "Rajesh P.", rating: 5, date: "1 month ago", comment: "Very professional and creative. Delivered on time with excellent quality. Will definitely work again.", brand: "FitLife" },
      { id: "r3", author: "Aisha B.", rating: 4, date: "1 month ago", comment: "Good quality content. Needed one extra revision but the final result was great.", brand: "StyleHouse" },
      { id: "r4", author: "Vikrant S.", rating: 5, date: "2 months ago", comment: "One of the best creators we've worked with. Understood the brief perfectly and delivered outstanding content.", brand: "TechNova" },
    ],
  };
}

export const CATEGORIES = [
  "All",
  "Fashion",
  "Beauty",
  "Tech",
  "Food",
  "Lifestyle",
  "Fitness",
] as const;

export const CITIES = [
  "All Cities",
  "Delhi",
  "Mumbai",
  "Bangalore",
  "Chennai",
  "Hyderabad",
  "Pune",
  "Jaipur",
] as const;
