-- Rename CreatorFacetDimension enum values (keeps existing data)
-- CASTING_TYPE -> CONTENT_FORMAT
-- LIFE_CONTEXT -> LIFE_STYLE
-- AVAILABLE_WITH -> CAN_CREATE_WITH

ALTER TYPE "CreatorFacetDimension" RENAME VALUE 'CASTING_TYPE' TO 'CONTENT_FORMAT';
ALTER TYPE "CreatorFacetDimension" RENAME VALUE 'LIFE_CONTEXT' TO 'LIFE_STYLE';
ALTER TYPE "CreatorFacetDimension" RENAME VALUE 'AVAILABLE_WITH' TO 'CAN_CREATE_WITH';

