/**
 * Invalidate existing card-preview renditions so they get re-generated by the
 * current pipeline.
 *
 * Why: the preview encode settings changed (e.g. 1080p / 9:16 / keep-audio), but
 * `PreviewVideoService` skips a row whose source is unchanged, so old renditions
 * would stick around forever. This nulls the preview fields and flips the row to
 * `pending`, which (a) makes the discovery card fall back to the intro / first
 * portfolio video immediately — `map-profile-to-creator.ts` falls back whenever
 * `previewVideoUrl` is null — and (b) makes the backfill/cron re-encode the row
 * from scratch with the deployed pipeline.
 *
 * Deploy the new pipeline FIRST. This only decides WHICH rows re-encode; the
 * encode itself runs whatever code is deployed. If you run this before deploying
 * the new `PreviewVideoService`, you just regenerate the old renditions.
 *
 * Crash-safe & resumable: nulling is idempotent, and each run only touches rows
 * that still carry a rendition, so the remaining count shrinks every run.
 *
 * Usage (from server/, after deploying the new pipeline):
 *   # dry run — prints how many rows would be invalidated, changes nothing:
 *   node dist/scripts/invalidate-preview-videos.js
 *   # actually invalidate (DB only; old S3 objects are left as orphans):
 *   APPLY=true node dist/scripts/invalidate-preview-videos.js
 *   # also delete the old preview objects from S3 (optional cleanup):
 *   APPLY=true PREVIEW_INVALIDATE_DELETE_OBJECTS=true \
 *     node dist/scripts/invalidate-preview-videos.js
 *
 * Then regenerate:  npm run backfill:preview-videos
 *
 * Env:
 *   APPLY=true                         execute (default dry-run)
 *   PREVIEW_INVALIDATE_DELETE_OBJECTS  also delete the old S3 preview object
 *   PREVIEW_INVALIDATE_BATCH           rows per page (default 100)
 * Requires the usual app env (DATABASE_URL, AWS_*, S3_BUCKET_NAME, CDN_BASE_URL).
 */
import { Logger, Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { NestFactory } from '@nestjs/core';
import { envValidationSchema } from '../config/env.validation';
import { PrismaModule } from '../prisma/prisma.module';
import { PrismaService } from '../prisma/prisma.service';
import { StorageModule } from '../storage/storage.module';
import { StorageService } from '../storage/storage.service';

const APPLY = process.env.APPLY === 'true';
const DELETE_OBJECTS = process.env.PREVIEW_INVALIDATE_DELETE_OBJECTS === 'true';

@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
      validationSchema: envValidationSchema,
      validationOptions: { abortEarly: true },
    }),
    PrismaModule,
    StorageModule,
  ],
})
class InvalidatePreviewModule {}

async function main(): Promise<void> {
  const logger = new Logger('invalidate-preview-videos');
  logger.log(
    APPLY
      ? `APPLY=true — preview fields WILL be cleared${DELETE_OBJECTS ? ' and old S3 objects deleted' : ''}`
      : 'DRY RUN — no changes will be made (set APPLY=true to execute)',
  );

  const batchSize = Math.max(
    1,
    Number(process.env.PREVIEW_INVALIDATE_BATCH) || 100,
  );

  const app = await NestFactory.createApplicationContext(
    InvalidatePreviewModule,
    { logger: ['error', 'warn', 'log'] },
  );
  const prisma = app.get(PrismaService);
  const storage = app.get(StorageService);

  // Rows that still carry a rendition (or a half-written one) to invalidate.
  const where = {
    OR: [
      { previewVideoKey: { not: null } },
      { previewVideoUrl: { not: null } },
      { previewVideoSourceKey: { not: null } },
    ],
  };

  let processed = 0;
  let deleted = 0;
  let errors = 0;

  try {
    const total = await prisma.creatorProfile.count({ where });
    logger.log(`remaining to invalidate: ${total} creator(s) with a rendition`);
    if (total === 0) {
      logger.log('nothing to invalidate — no renditions found');
      return;
    }

    let cursor: string | undefined;
    for (;;) {
      const batch = await prisma.creatorProfile.findMany({
        where,
        select: { id: true, previewVideoKey: true },
        orderBy: { id: 'asc' },
        take: batchSize,
        ...(cursor ? { cursor: { id: cursor }, skip: 1 } : {}),
      });
      if (batch.length === 0) break;

      for (const row of batch) {
        processed++;
        if (!APPLY) continue;
        try {
          // Null the fields FIRST so the card falls back immediately and the
          // backfill re-encodes; only then (optionally) drop the old object.
          await prisma.creatorProfile.update({
            where: { id: row.id },
            data: {
              previewVideoUrl: null,
              previewVideoKey: null,
              previewVideoSourceKey: null,
              previewVideoStatus: 'pending',
              previewVideoAttempts: 0,
            },
          });
          if (DELETE_OBJECTS && row.previewVideoKey) {
            await storage
              .deleteObjectIfExists(row.previewVideoKey)
              .catch(() => undefined);
            deleted++;
          }
        } catch (err) {
          errors++;
          logger.error(
            `invalidate failed for creator ${row.id}: ${(err as Error)?.message}`,
          );
        }
      }

      cursor = batch[batch.length - 1].id;
      logger.log(`progress: ${processed}/${total}${APPLY ? '' : ' [dry-run]'}`);
    }

    logger.log(
      `${APPLY ? 'invalidate complete' : 'dry run complete'}: ${processed} processed, ` +
        `${deleted} old object(s) deleted, ${errors} errors. ` +
        `Now run: npm run backfill:preview-videos`,
    );
  } finally {
    await app.close();
  }
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error('invalidate-preview-videos crashed:', err);
    process.exit(1);
  });
